query providerOperatingTimesQuery($providerId: Int!) {
  providerOperatingTimes(providerId: $providerId) {
    id
    day {
      id
      day
    }
    time {
      id
      startTime
      endTime
    }
  }
}
